version: '3.3'
services:
    dhcp-server:
        container_name: dhcp
        image: 'sadviper/dhcpd-ha:0.1'
        environment:
            - HA=true
            # Env used in HA Failover not required if not HA=true
            - ROLE=PRIMARY
            - PEER_ADDRESS=169.254.1.1
            - HA_PORT=647
            - MAX_RESPONSE_DELAY=15
            - MAX_UNACKED_UPDATES=10
            - LOAD_BALANCE_MAX_SECONDS=3
            - MCLT=3600
            - SPLIT=128
        ports:
            - '67:67/udp'
            - '647:647/tcp' # HA failover port
        volumes:
            - ./runtime:/data # Save dhcpd.conf and dhcpd.leases
